const ActionType = {
    SET_PRODUCT : "SET_PRODUCT",
    SELECT_PRODUCT:"SELECT_PRODUCT",
    REMOVE_SELECT_PRODUCT:"REMOVE_SELECT_PRODUCT",
    ADDTOCART:"ADDTOCART",
    DELETETOCART:"DELETETOCART"
}
export default ActionType;